// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectHiddenVillage.Server.Data;

#nullable disable

namespace ProjectHiddenVillage.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260806160037_AddJoinCodeToGameInstances")]
    partial class AddJoinCodeToGameInstances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.CardCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribute")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EffectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Life")
                        .HasColumnType("integer");

                    b.Property<bool>("MainAlternate")
                        .HasColumnType("boolean");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<int?>("SupportCost")
                        .HasColumnType("integer");

                    b.Property<string>("SupportEffect")
                        .HasColumnType("text");

                    b.Property<string>("SupportName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TraitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("card_catalog_entries", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("decks", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.DeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardCatalogEntryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CardCatalogEntryId");

                    b.HasIndex("DeckId");

                    b.HasIndex("DeckId", "CardCatalogEntryId")
                        .IsUnique();

                    b.ToTable("deck_cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_deck_cards_quantity_positive", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.GameInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.PrimitiveCollection<bool[]>("Player1CurrentChakras")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean[]")
                        .HasDefaultValueSql("ARRAY[TRUE, TRUE, TRUE, TRUE, TRUE, TRUE]");

                    b.Property<Guid>("Player1DeckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Player1SummonCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("Player1UserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<bool[]>("Player2CurrentChakras")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean[]")
                        .HasDefaultValueSql("ARRAY[TRUE, TRUE, TRUE, TRUE, TRUE, TRUE]");

                    b.Property<Guid>("Player2DeckId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Player2SummonCard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("Player2UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("Player1DeckId");

                    b.HasIndex("Player1UserId");

                    b.HasIndex("Player2DeckId");

                    b.HasIndex("Player2UserId");

                    b.ToTable("game_instances", null, t =>
                        {
                            t.HasCheckConstraint("CK_game_instances_join_code_format", "\"JoinCode\" ~ '^[A-Za-z0-9]{5}$'");

                            t.HasCheckConstraint("CK_game_instances_player1_current_chakras_length", "cardinality(\"Player1CurrentChakras\") = 6");

                            t.HasCheckConstraint("CK_game_instances_player2_current_chakras_length", "cardinality(\"Player2CurrentChakras\") = 6");

                            t.HasCheckConstraint("CK_game_instances_player_decks_different", "\"Player1DeckId\" <> \"Player2DeckId\"");

                            t.HasCheckConstraint("CK_game_instances_player_users_different", "\"Player1UserId\" <> \"Player2UserId\"");
                        });
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.GameLogArchiveEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("GameId");

                    b.ToTable("game_log_archives", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1CharacterFieldCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player1_character_field_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1RuntimeDeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player1_runtime_deck_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1SupportAreaCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player1_support_area_cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_player1_support_area_cards_position_range", "\"Position\" >= 1 AND \"Position\" <= 5");
                        });
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1TrashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player1_trash_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2CharacterFieldCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player2_character_field_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2RuntimeDeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player2_runtime_deck_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2SupportAreaCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player2_support_area_cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_player2_support_area_cards_position_range", "\"Position\" >= 1 AND \"Position\" <= 5");
                        });
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2TrashCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("GameInstanceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameInstanceId");

                    b.HasIndex("GameInstanceId", "Position")
                        .IsUnique();

                    b.ToTable("player2_trash_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("saved_decks", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavedDeckId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SavedDeckId");

                    b.HasIndex("SavedDeckId", "CardId")
                        .IsUnique();

                    b.ToTable("saved_deck_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Deck", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.DeckCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.CardCatalogEntry", "CardCatalogEntry")
                        .WithMany()
                        .HasForeignKey("CardCatalogEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardCatalogEntry");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.GameInstance", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.Deck", "Player1Deck")
                        .WithMany()
                        .HasForeignKey("Player1DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.User", "Player1User")
                        .WithMany("Player1GameInstances")
                        .HasForeignKey("Player1UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.Deck", "Player2Deck")
                        .WithMany()
                        .HasForeignKey("Player2DeckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.User", "Player2User")
                        .WithMany("Player2GameInstances")
                        .HasForeignKey("Player2UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player1Deck");

                    b.Navigation("Player1User");

                    b.Navigation("Player2Deck");

                    b.Navigation("Player2User");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1CharacterFieldCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player1CharacterFieldCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1RuntimeDeckCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player1RuntimeDeckCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1SupportAreaCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player1SupportAreaCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player1TrashCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player1TrashCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2CharacterFieldCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player2CharacterFieldCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2RuntimeDeckCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player2RuntimeDeckCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2SupportAreaCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player2SupportAreaCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Player2TrashCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.GameInstance", "GameInstance")
                        .WithMany("Player2TrashCards")
                        .HasForeignKey("GameInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameInstance");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.User", "User")
                        .WithMany("SavedDecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeckCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", "SavedDeck")
                        .WithMany("Cards")
                        .HasForeignKey("SavedDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedDeck");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.GameInstance", b =>
                {
                    b.Navigation("Player1CharacterFieldCards");

                    b.Navigation("Player1RuntimeDeckCards");

                    b.Navigation("Player1SupportAreaCards");

                    b.Navigation("Player1TrashCards");

                    b.Navigation("Player2CharacterFieldCards");

                    b.Navigation("Player2RuntimeDeckCards");

                    b.Navigation("Player2SupportAreaCards");

                    b.Navigation("Player2TrashCards");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.User", b =>
                {
                    b.Navigation("Decks");

                    b.Navigation("Player1GameInstances");

                    b.Navigation("Player2GameInstances");

                    b.Navigation("SavedDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
