// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectHiddenVillage.Server.Data;

#nullable disable

namespace ProjectHiddenVillage.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803140225_AddCardCatalogEntries")]
    partial class AddCardCatalogEntries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.CardCatalogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Attribute")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Color")
                        .HasColumnType("integer");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Damage")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EffectsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int?>("Health")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int?>("Life")
                        .HasColumnType("integer");

                    b.Property<bool>("MainAlternate")
                        .HasColumnType("boolean");

                    b.Property<string>("NameJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OriginalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Power")
                        .HasColumnType("integer");

                    b.Property<int?>("SupportCost")
                        .HasColumnType("integer");

                    b.Property<string>("SupportEffect")
                        .HasColumnType("text");

                    b.Property<string>("SupportName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("TraitsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("card_catalog_entries", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.GameLogArchiveEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("GameId");

                    b.ToTable("game_log_archives", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("saved_decks", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeckCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CardId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavedDeckId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SavedDeckId");

                    b.HasIndex("SavedDeckId", "CardId")
                        .IsUnique();

                    b.ToTable("saved_deck_cards", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.User", "User")
                        .WithMany("SavedDecks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeckCard", b =>
                {
                    b.HasOne("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", "SavedDeck")
                        .WithMany("Cards")
                        .HasForeignKey("SavedDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SavedDeck");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.SavedDeck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ProjectHiddenVillage.Server.Data.Entities.User", b =>
                {
                    b.Navigation("SavedDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
